;/*FB_PKG_DELIM*/

__d("CometAdActivityConstants",["$InternalEnum"],(function(a,b,c,d,e,f){"use strict";a=b("$InternalEnum").Mirrored(["Recent","Saved"]);c=[a.Recent,a.Saved];d=10;e="bookmark";var g={CLICK_AD:"click_ad",REPORT_AD:"report_ad",SAVE_AD:"save_ad",SEE_MORE:"click_see_more",TAB_RECENT:"recent_activity_tab",TAB_SAVED:"saved_ads_tab",UNSAVE_AD:"unsave_ad"},h={CLICKED:"clicked",SAVED:"saved"};b=b("$InternalEnum").Mirrored(["Locked","Unlocked","None"]);f.CometAdActivityTabGroup=a;f.CometAdActivityTabs=c;f.COMET_AD_ACTIVITY_REFETCH_LIMIT=d;f.SOURCE=e;f.CLICK_TYPE=g;f.TAB_TYPE=h;f.GatedContent=b}),66);
__d("CometAdActivityRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5643267092430362"}),null);
__d("CometAdActivityRootQuery$Parameters",["CometAdActivityRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometAdActivityRootQuery_facebookRelayOperation"),metadata:{},name:"CometAdActivityRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometAdActivityRootEntryPoint.entrypoint",["CometAdActivityRootQuery$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(){return{queries:{adActivityRootQueryReference:{parameters:b("CometAdActivityRootQuery$Parameters"),variables:{count:20}}}}},root:c("JSResourceForInteraction")("CometAdActivityRoot.react").__setRef("CometAdActivityRootEntryPoint.entrypoint")};g["default"]=a}),98);
__d("CometBookmarksRoot.entrypoint",["CometClassicHomeLeftRailContainerQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=(a=(a=a.routeProps)==null?void 0:a.isEligibleForProfessionalTools)!=null?a:!1;var b=10;a&&(b-=2);return{queries:{menuContainerQueryReference:{parameters:c("CometClassicHomeLeftRailContainerQuery$Parameters"),variables:{isEligibleForProfessionalTools:a,numExploreBookmarks:b,numShortcutBookmarks:5,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("CometBookmarksRoot.react").__setRef("CometBookmarksRoot.entrypoint")};g["default"]=a}),98);
__d("CometGamingVideoRootContentQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="27534093732902203"}),null);
__d("CometGamingVideoRootContentQuery$Parameters",["CometGamingVideoRootContentQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometGamingVideoRootContentQuery_facebookRelayOperation"),metadata:{},name:"CometGamingVideoRootContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGamingVideoRootHeroBannerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="28096474659939802"}),null);
__d("CometGamingVideoRootHeroBannerQuery$Parameters",["CometGamingVideoRootHeroBannerQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometGamingVideoRootHeroBannerQuery_facebookRelayOperation"),metadata:{},name:"CometGamingVideoRootHeroBannerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGamingVideoRoot.entrypoint",["CometGamingVideoRootContentQuery$Parameters","CometGamingVideoRootHeroBannerQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometGamingRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometGamingRoute.entrypoint")("GAMING_VIDEO")(c("JSResourceForInteraction")("CometGamingVideoRoot.react").__setRef("CometGamingVideoRoot.entrypoint"),function(a){a=a.routeParams;var c=d("WebPixelRatio").get();return{queries:{contentQueryReference:{parameters:b("CometGamingVideoRootContentQuery$Parameters"),variables:{scale:c}},heroBannerQueryReference:{parameters:b("CometGamingVideoRootHeroBannerQuery$Parameters"),variables:{videoID:a.video_id}}}}});g["default"]=a}),98);
__d("CometPublicPresenceOnboardingDialog.entrypoint",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(){return{queries:{}}},root:c("JSResourceForInteraction")("CometPublicPresenceOnboardingDialog.react").__setRef("CometPublicPresenceOnboardingDialog.entrypoint")};g["default"]=a}),98);
__d("DiscoveryHubCometContentQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8894881703957706"}),null);
__d("DiscoveryHubCometContentQuery$Parameters",["CometFeedStoryDynamicResolutionPhotoAttachmentRenderer_experimentWidth.relayprovider","CometImmersivePhotoCanUserDisable3DMotion.relayprovider","CometUFIReactionsEnableShortName.relayprovider","CometUFIShareActionMigration.relayprovider","DiscoveryHubCometContentQuery_facebookRelayOperation","EventCometCardImage_prefetchEventImage.relayprovider","FBReelsMediaFooter_comet_enable_reels_ads_gk.relayprovider","GHLShouldChangeAdIdFieldName.relayprovider","GHLShouldChangeSponsoredDataFieldName.relayprovider","IsMergQAPolls.relayprovider","IsWorkUser.relayprovider","StoriesArmadilloReplyEnabled.relayprovider"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("DiscoveryHubCometContentQuery_facebookRelayOperation"),metadata:{},name:"DiscoveryHubCometContentQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__GHLShouldChangeSponsoredDataFieldNamerelayprovider:b("GHLShouldChangeSponsoredDataFieldName.relayprovider"),__relay_internal__pv__GHLShouldChangeAdIdFieldNamerelayprovider:b("GHLShouldChangeAdIdFieldName.relayprovider"),__relay_internal__pv__IsWorkUserrelayprovider:b("IsWorkUser.relayprovider"),__relay_internal__pv__CometFeedStoryDynamicResolutionPhotoAttachmentRenderer_experimentWidthrelayprovider:b("CometFeedStoryDynamicResolutionPhotoAttachmentRenderer_experimentWidth.relayprovider"),__relay_internal__pv__CometImmersivePhotoCanUserDisable3DMotionrelayprovider:b("CometImmersivePhotoCanUserDisable3DMotion.relayprovider"),__relay_internal__pv__IsMergQAPollsrelayprovider:b("IsMergQAPolls.relayprovider"),__relay_internal__pv__FBReelsMediaFooter_comet_enable_reels_ads_gkrelayprovider:b("FBReelsMediaFooter_comet_enable_reels_ads_gk.relayprovider"),__relay_internal__pv__CometUFIReactionsEnableShortNamerelayprovider:b("CometUFIReactionsEnableShortName.relayprovider"),__relay_internal__pv__CometUFIShareActionMigrationrelayprovider:b("CometUFIShareActionMigration.relayprovider"),__relay_internal__pv__StoriesArmadilloReplyEnabledrelayprovider:b("StoriesArmadilloReplyEnabled.relayprovider"),__relay_internal__pv__EventCometCardImage_prefetchEventImagerelayprovider:b("EventCometCardImage_prefetchEventImage.relayprovider")}}};e.exports=a}),null);
__d("DiscoveryHubCometFeed.variables",["WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";var h={feedbackSource:93,feedLocation:"COMET_RACIAL_JUSTICE_HUB_FEED",focusCommentID:null,privacySelectorRenderLocation:"COMET_RACIAL_JUSTICE_HUB",renderLocation:"discovery_hub_feed",scale:d("WebPixelRatio").get(),useDefaultActor:!1};function a(a,b){return babelHelpers["extends"]({},h,{feedLocation:b,renderLocation:a})}g.variables=h;g.getFeedVariables=a}),98);
__d("DiscoveryHubCometFooterQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8601375869949148"}),null);
__d("DiscoveryHubCometFooterQuery$Parameters",["DiscoveryHubCometFooterQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("DiscoveryHubCometFooterQuery_facebookRelayOperation"),metadata:{},name:"DiscoveryHubCometFooterQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("DiscoveryHubCometHeaderQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8614313675354025"}),null);
__d("DiscoveryHubCometHeaderQuery$Parameters",["DiscoveryHubCometHeaderQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("DiscoveryHubCometHeaderQuery_facebookRelayOperation"),metadata:{},name:"DiscoveryHubCometHeaderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("DiscoveryHubCometStickyHeaderQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8535441549865417"}),null);
__d("DiscoveryHubCometStickyHeaderQuery$Parameters",["DiscoveryHubCometStickyHeaderQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("DiscoveryHubCometStickyHeaderQuery_facebookRelayOperation"),metadata:{},name:"DiscoveryHubCometStickyHeaderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("DiscoveryHubCometRoot.entrypoint",["DiscoveryHubCometContentQuery$Parameters","DiscoveryHubCometFeed.variables","DiscoveryHubCometFooterQuery$Parameters","DiscoveryHubCometHeaderQuery$Parameters","DiscoveryHubCometStickyHeaderQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.routeProps;var b=a.feed_location,e=a.hoisted_content_ids,f=a.hoisted_fav,g=a.hoisted_unit_ids,h=a.hub,i=a.state,j=a.state_override;a=a.story_render_location;var k=d("WebPixelRatio").get();a=d("DiscoveryHubCometFeed.variables").getFeedVariables(a,b);return{queries:{contentQuery:{parameters:c("DiscoveryHubCometContentQuery$Parameters"),variables:babelHelpers["extends"]({},a,{hoisted_content_ids:e,hoisted_fav:f,hoisted_unit_ids:g,hub:h,scale:k,state:i,stateOverride:j})},footerQuery:{parameters:c("DiscoveryHubCometFooterQuery$Parameters"),variables:{hub:h,scale:k}},headerQuery:{parameters:c("DiscoveryHubCometHeaderQuery$Parameters"),variables:{hub:h,scale:k}},stickyHeaderQuery:{parameters:c("DiscoveryHubCometStickyHeaderQuery$Parameters"),variables:{hub:h,scale:k}}}}},root:c("JSResourceForInteraction")("DiscoveryHubCometRoot.react").__setRef("DiscoveryHubCometRoot.entrypoint")};g["default"]=a}),98);
__d("MessengerKidsCometAppQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5245555968788039"}),null);
__d("MessengerKidsCometAppQuery$Parameters",["MessengerKidsCometAppQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("MessengerKidsCometAppQuery_facebookRelayOperation"),metadata:{connection:[{count:null,cursor:null,direction:"forward",path:["viewer","actor","managed_neo_approved_users"]}]},name:"MessengerKidsCometAppQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("MessengerKidsCometRoot.entrypoint",["JSResourceForInteraction","MessengerKidsCometAppQuery$Parameters","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(){return{queries:{messengerKidsCometRootQueryReference:{parameters:b("MessengerKidsCometAppQuery$Parameters"),variables:{scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("MessengerKidsCometRoot.react").__setRef("MessengerKidsCometRoot.entrypoint")};g["default"]=a}),98);