;/*FB_PKG_DELIM*/

__d("CometComposerLinksPluginForLexicalDeferred.react",["createComposerDeferredPlugin","react","requireDeferred"],(function(a,b,c,d,e,f,g){"use strict";var h;h||d("react");a=c("createComposerDeferredPlugin")(c("requireDeferred")("CometComposerLinksPluginForLexicalWithDefaultExport.react").__setRef("CometComposerLinksPluginForLexicalDeferred.react"));g["default"]=a}),98);
__d("CometEventPermalinkTab",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum")({ABOUT:"about",DISCUSSION:"discussion",BRACKETS:"brackets",BROADCASTS:"broadcasts",PARTICIPANTS:"participants",STANDINGS:"standings",VIDEOS:"videos",PAID_ACCESS:"paid_access"});c=a;f["default"]=c}),66);
__d("EventCometActionContextDefault",[],(function(a,b,c,d,e,f){"use strict";a={event_action_history:[]};f["default"]=a}),66);
__d("EventCometActionContext",["EventCometActionContextDefault","react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext(c("EventCometActionContextDefault"));g["default"]=b}),98);
__d("EventCometActionLoggerUtils",["CometRouteURL"],(function(a,b,c,d,e,f,g){"use strict";var h={mechanism:"unknown",surface:"unknown"},i=3;function a(a,b){var c=[].concat(a.event_action_history||[]);c.length>=i&&(c=c.slice(c.length-i+1));var d=j(a);c.push({event_tracking:d.event_tracking,extra_data:d.extra_data,mechanism:b.mechanism,surface:b.surface});return babelHelpers["extends"]({},a,{event_action_history:c})}function j(a){a=a.event_action_history;if(a==null||a[a.length-1]==null)return h;return a.length>=2?a[a.length-2]:a[a.length-1]}function b(){var a=d("CometRouteURL").useRouteURL(),b=/\/events\/\d+/;if(b.test(a))return"permalink";if(a.includes("/events/calendar"))return"bookmark_calendar";if(a.includes("/events"))return"bookmark";return a.includes("profile.php")?"timeline":"newsfeed"}g.createForNewSurface=a;g.getLastActionHistoryEntry=j;g.useExtractEventComposerSurface=b}),98);
__d("XCometEventPermalinkControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/events/{event_id}/{?child_event_id}/",Object.freeze({active_tab:"about",show_created_event_toast:!1,hide_invite_flow_filter_groups:!1,show_join_in_vr_dialog:!1}),void 0);b=a;g["default"]=b}),98);
__d("castToEnum",[],(function(a,b,c,d,e,f){"use strict";function a(a,b,c){var d=Object.keys(b);for(var e=0;e<d.length;e++)if(b[d[e]]===a)return b[d[e]];return c}f["default"]=a}),66);
__d("cometFormattedTextIneligibilityCheck",[],(function(a,b,c,d,e,f){"use strict";function a(a,b,c){var d;b===void 0&&(b=130);c===void 0&&(c=3);return((d=(d=a.match(/\n/g))==null?void 0:d.length)!=null?d:0)>=c||a.length>b}f["default"]=a}),66);
__d("distinctArray",[],(function(a,b,c,d,e,f){function a(a){if(a==null)return[];if(Array.isArray(a)){var b=a.length;if(b<=200){var c=[];for(var d=0;d<b;d++){var e=a[d];c.indexOf(e)===-1&&c.push(e)}return c}}return Array.from(new Set(a).values())}f["default"]=a}),66);
__d("mapMapToArray",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){var c=[],d=0;for(var e=a,f=Array.isArray(e),g=0,e=f?e:e[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var h;if(f){if(g>=e.length)break;h=e[g++]}else{g=e.next();if(g.done)break;h=g.value}h=h;var i=h[0];h=h[1];c.push(b(h,i,d,a));d++}return c}f["default"]=a}),66);
__d("useBaseDynamicEntryPointDialog",["CometDialogContext","CometRelay","CometSuspendedDialogImpl.react","clearTimeout","react","react-compiler-runtime","setTimeout","tracePolicyFromResource","useCometRelayEntrypointContextualEnvironmentProvider"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;b.useCallback;var j=b.useContext,k=b.useEffect,l=b.useRef;function m(a){var b=d("react-compiler-runtime").c(17),e=a.entryPoint,f=a.environmentProvider,g=a.onClose,h=a.otherProps,j=a.overrideRelayEnv,m=a.preloadedEntryPoint,n=a.preloadParams;a=d("CometRelay").useEntryPointLoader(f,e);var o=a[0],p=a[1],q=a[2],r=(f=o)!=null?f:m,s=l(null);b[0]!==q||b[1]!==r.isDisposed||b[2]!==n||b[3]!==m||b[4]!==p||b[5]!==o?(e=function(){s.current!=null&&(c("clearTimeout")(s.current),s.current=null);r.isDisposed&&p(n);return function(){s.current=c("setTimeout")(function(){o?q():m.dispose(),s.current=null},6e4)}},a=[q,r.isDisposed,m,n,p,o],b[0]=q,b[1]=r.isDisposed,b[2]=n,b[3]=m,b[4]=p,b[5]=o,b[6]=e,b[7]=a):(e=b[6],a=b[7]);k(e,a);b[8]!==g||b[9]!==h?(f=babelHelpers["extends"]({},h,{onClose:g}),b[8]=g,b[9]=h,b[10]=f):f=b[10];e=f;b[11]!==m||b[12]!==e?(a=i.jsx(d("CometRelay").EntryPointContainer,{entryPointReference:m,props:e}),b[11]=m,b[12]=e,b[13]=a):a=b[13];g=a;b[14]!==g||b[15]!==j?(h=j!=null?i.jsx(d("CometRelay").RelayEnvironmentProvider,{environment:j,children:g}):g,b[14]=g,b[15]=j,b[16]=h):h=b[16];return h}function a(a,b,e,f){var g=d("react-compiler-runtime").c(7),h=c("useCometRelayEntrypointContextualEnvironmentProvider")(f),i=j(c("CometDialogContext")),k;g[0]!==i||g[1]!==a||g[2]!==h||g[3]!==e||g[4]!==f||g[5]!==b?(k=function(g,j,k,l){var n=d("CometRelay").loadEntryPoint(h,a,g),o=function(){for(var a=arguments.length,b=new Array(a),c=0;c<a;c++)b[c]=arguments[c];var d=b;k&&k.apply(void 0,d);var e=n==null?void 0:n.dispose;e&&e()};i(c("CometSuspendedDialogImpl.react"),{dialog:m,dialogProps:{entryPoint:a,environmentProvider:h,otherProps:j,overrideRelayEnv:f,preloadedEntryPoint:n,preloadParams:g},fallback:e},{loadType:"entrypoint",preloadTrigger:b,tracePolicy:(j=l)!=null?j:c("tracePolicyFromResource")("comet.dialog",a.root)},o)},g[0]=i,g[1]=a,g[2]=h,g[3]=e,g[4]=f,g[5]=b,g[6]=k):k=g[6];return k}g["default"]=a}),98);
__d("useCometDynamicEntryPointDialog",["FDSDialogLoadingState.react","react","useBaseDynamicEntryPointDialog"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react"),j=function(a){return i.jsx(c("FDSDialogLoadingState.react"),{onClose:a})};function a(a,b,d,e){return c("useBaseDynamicEntryPointDialog")(a,b,(a=d)!=null?a:j,e)}g["default"]=a}),98);
__d("useFileDragEvents",["react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");b.useCallback;var i=b.useEffect,j=b.useRef,k=b.useState;function a(a,b,c){var e=d("react-compiler-runtime").c(13),f=b===void 0?document.documentElement:b,g=j(0);b=k(!1);var h=b[0],m=b[1];e[0]!==a||e[1]!==c?(b=function(b){m(!1);if((c==null||c(b))&&a!=null){b.preventDefault();var d=b.dataTransfer;if(d!=null){d=d.files;a(d,b)!==!1&&b.stopPropagation()}else b.stopPropagation();g.current=0}},e[0]=a,e[1]=c,e[2]=b):b=e[2];var n=b;e[3]!==c?(b=function(a){var b;b=(b=a.dataTransfer)==null?void 0:b.files;(c==null||c(a))&&b!=null&&(a.preventDefault(),g.current=g.current+1,m(!0))},e[3]=c,e[4]=b):b=e[4];var o=b;e[5]!==c?(b=function(a){var b;b=(b=a.dataTransfer)==null?void 0:b.files;(c==null||c(a))&&b!=null&&(g.current=g.current-1)===0&&m(!1)},e[5]=c,e[6]=b):b=e[6];var p=b,q=l,r;e[7]!==o||e[8]!==p||e[9]!==n||e[10]!==f?(b=function(){if(f!=null){f.addEventListener("drop",n,!0);f.addEventListener("dragenter",o,!0);f.addEventListener("dragleave",p,!0);f.addEventListener("dragover",q,!0);return function(){f.removeEventListener("drop",n,!0),f.removeEventListener("dragenter",o,!0),f.removeEventListener("dragleave",p,!0),f.removeEventListener("dragover",q,!0)}}},r=[o,p,q,n,f],e[7]=o,e[8]=p,e[9]=n,e[10]=f,e[11]=b,e[12]=r):(b=e[11],r=e[12]);i(b,r);return h}function l(a){var b;b=(b=a.dataTransfer)==null?void 0:b.files;a.dataTransfer!=null&&(a.dataTransfer.dropEffect="copy");b!=null&&a.preventDefault()}g["default"]=a}),98);
__d("useShallowEqualMemo",["shallowEqual","useCustomEqualityMemo"],(function(a,b,c,d,e,f,g){"use strict";function a(a){return c("useCustomEqualityMemo")(a,c("shallowEqual"))}g["default"]=a}),98);