;/*FB_PKG_DELIM*/

__d("AdsLWICometAPPlusLeftNavLayoutExperimentUtils",["qex"],(function(a,b,c,d,e,f,g){"use strict";a=function(){var a;return(a=c("qex")._("433"))!=null?a:!1};g.isAPPlusLeftNavLayoutChangeEnabled=a}),98);
__d("CometProfilePlusCreatePreferredInteractionDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9192633304082004"}),null);
__d("CometProfilePlusCreatePreferredInteractionDialogQuery$Parameters",["CometProfilePlusCreatePreferredInteractionDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometProfilePlusCreatePreferredInteractionDialogQuery_facebookRelayOperation"),metadata:{},name:"CometProfilePlusCreatePreferredInteractionDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometProfilePlusCreatePreferredInteractionDialog.entrypoint",["CometProfilePlusCreatePreferredInteractionDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.profileID;return{queries:{queryReference:{parameters:b("CometProfilePlusCreatePreferredInteractionDialogQuery$Parameters"),variables:{profileID:a,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("CometProfilePlusCreatePreferredInteractionDialog.react").__setRef("CometProfilePlusCreatePreferredInteractionDialog.entrypoint")};g["default"]=a}),98);
__d("CometProfilePlusLeftNavMenuActionClickLogger",["requireDeferred"],(function(a,b,c,d,e,f,g){"use strict";var h=c("requireDeferred")("CometProfilePlusLeftNavMenuActionFalcoEvent").__setRef("CometProfilePlusLeftNavMenuActionClickLogger");function a(a,b,c){h.onReady(function(d){d.log(function(){return{action_identifier:a,action_type:"click",is_pplus_ads_update:c,profile_id:b}})});return}g.logCometProfilePlusLeftNavMenuActionClick=a}),98);
__d("CometWhatsappSMBDialogV2Query_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7290614421051898"}),null);
__d("CometWhatsappSMBDialogV2Query$Parameters",["CometWhatsappSMBDialogV2Query_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometWhatsappSMBDialogV2Query_facebookRelayOperation"),metadata:{live:{polling_interval:2500}},name:"CometWhatsappSMBDialogV2Query",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometWhatsappSMBDialogV2.entrypoint",["CometWhatsappSMBDialogV2Query$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{queryReference:{parameters:c("CometWhatsappSMBDialogV2Query$Parameters"),variables:{pageID:a.pageID}}}}},root:c("JSResourceForInteraction")("CometWhatsappSMBDialogV2.react").__setRef("CometWhatsappSMBDialogV2.entrypoint")};g["default"]=a}),98);
__d("PagesCometComposerDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8973521559370648"}),null);
__d("PagesCometComposerDialogQuery$Parameters",["PagesCometComposerDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PagesCometComposerDialogQuery_facebookRelayOperation"),metadata:{},name:"PagesCometComposerDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PagesCometComposerDialog.entrypoint",["JSResourceForInteraction","PagesCometComposerDialogQuery$Parameters","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.id;return{queries:{dialogQueryReference:{parameters:b("PagesCometComposerDialogQuery$Parameters"),variables:{id:a,privacySelectorRenderLocation:"COMET_COMPOSER",scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("PagesCometComposerDialog.react").__setRef("PagesCometComposerDialog.entrypoint")};g["default"]=a}),98);
__d("PagesCometComposerPrivacySelectorConstants",[],(function(a,b,c,d,e,f){"use strict";a=13;b={};c=["CITY","COUNTRY","REGION"];d={allow:[],base_state:"EVERYONE",deny:[],tag_expansion_state:"UNSPECIFIED"};e=Object.freeze({DEFAULT_AGE:a,DEFAULT_LOCATION_API_SPEC:b,DEFAULT_PRIVACY_ROW_INPUT:d,LOCATION_TYPES:c});f["default"]=e}),66);
__d("ProgressiveDateUtil",["DateConsts"],(function(a,b,c,d,e,f,g){"use strict";function h(a){var b=a.day,c=a.month;a=a.year;if(a==null)return Object.freeze({});if(c==null)return{year:a};if(b==null)return{month:c,year:a};var e=d("DateConsts").getDaysInMonth(a,c);return b>e?{day:e,month:c,year:a}:{day:b,month:c,year:a}}function a(a){if(a==null)return{};a=a.split("-").map(function(a){return parseInt(a,10)});var b=a[0],c=a[1];a=a[2];return h({day:a,month:c,year:b})}function b(a){var b=null;a.day!=null&&(b=a.day);var c=null;a.month!=null&&(c=a.month);var d=null;a.year!=null&&(d=a.year);return{day:b,month:c,year:d}}function c(a){var b=null;a.day!=null&&a.month!=null&&a.year!=null?b=new Date(a.year,a.month-1,a.day+1):a.month!=null&&a.year!=null?b=new Date(a.year,a.month,1):a.year!=null&&(b=new Date(a.year+1,0,1));return b!=null?b.setSeconds(-1)/1e3:null}g.makeValidDate=h;g.parseDate=a;g.toMaybeDate=b;g.toLatestTimestamp=c}),98);
__d("ProfileCometTimelineFilterReducer",["ProgressiveDateUtil"],(function(a,b,c,d,e,f,g){"use strict";a=function(){return{date:{},hasBeenChanged:!1,postedBy:"ANYONE",privacy:"ALL",taggedPosts:"ALL"}};b=function(a,b){switch(b.type){case"SET_FILTERS":var c=d("ProgressiveDateUtil").makeValidDate(d("ProgressiveDateUtil").toMaybeDate(b.date));return babelHelpers["extends"]({},a,{date:c,hasBeenChanged:!0,postedBy:b.postedBy,privacy:b.privacy,taggedPosts:b.taggedPosts});default:return babelHelpers["extends"]({},a)}};g.getInitialState=a;g.reducer=b}),98);
__d("ProfileCometTimelineFilterContext",["FBLogger","ProfileCometTimelineFilterReducer","react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext({dispatchAction:function(a){c("FBLogger")("comet_profile").mustfix("ProfileCometTimelineFilterContext: Tried to dispatch an action\n        without providing a dispatch function. Please render this component with\n        a context provider, e.g.:\n        <ProfileCometTimelineFilterContext.Provider value={context} />")},state:d("ProfileCometTimelineFilterReducer").getInitialState()});g["default"]=b}),98);
__d("useCometPageComposerDialog",["fbt","FDSCardedDialogLegacy.react","FeedComposerCometGlimmer.react","PagesCometComposerDialog.entrypoint","emptyFunction","react","react-compiler-runtime","useCometEntryPointDialog"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j=i||(i=d("react"));b=i;b.useCallback;var k=b.useRef,l={withCloseButton:!0};function m(a){var b=d("react-compiler-runtime").c(3),e;b[0]===Symbol["for"]("react.memo_cache_sentinel")?(e=j.jsx(c("FeedComposerCometGlimmer.react"),{}),b[0]=e):e=b[0];b[1]!==a?(e=j.jsx("div",{children:j.jsx(c("FDSCardedDialogLegacy.react"),babelHelpers["extends"]({size:"content",title:a.title},a,{children:e}))}),b[1]=a,b[2]=e):e=b[2];return e}function a(a){var b=d("react-compiler-runtime").c(19),e=a.actorID,f=a.composerEntryPointRef,g=a.composerType,i=a.onBeforeClose,n=a.onSave,o=a.pageID,p=a.title,q;b[0]!==p?(q=p===void 0?h._(/*BTDS*/"__JHASH__NvAL689IQ7h__JHASH__"):p,b[0]=p,b[1]=q):q=b[1];var r=q,s=(p=a.onClose)!=null?p:c("emptyFunction");q=k(null);b[2]!==o?(a={id:o},b[2]=o,b[3]=a):a=b[3];b[4]!==r?(p=function(){return j.jsx(m,babelHelpers["extends"]({title:r},l))},b[4]=r,b[5]=p):p=b[5];a=c("useCometEntryPointDialog")(c("PagesCometComposerDialog.entrypoint"),a,void 0,p);var t=a[0];p=a[1];b[6]!==e||b[7]!==f||b[8]!==g||b[9]!==i||b[10]!==s||b[11]!==n||b[12]!==o||b[13]!==t||b[14]!==r?(a=function(a){a=a||{};var b=a.beginningViewState;a=a.pushedPageOnLoad;t(babelHelpers["extends"]({actorID:e,beginningViewState:b,composerEntryPointRef:f,composerType:g,onBeforeClose:i,onClose:s,onSave:n,pageID:o,pushedPageOnLoad:a,title:r},l),s)},b[6]=e,b[7]=f,b[8]=g,b[9]=i,b[10]=s,b[11]=n,b[12]=o,b[13]=t,b[14]=r,b[15]=a):a=b[15];a=a;b[16]!==p||b[17]!==a?(q=[a,q,p],b[16]=p,b[17]=a,b[18]=q):q=b[18];return q}g["default"]=a}),226);